In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Requisição e selecação

In [12]:
# Função para realizar o WebScraping
def extrair_info_estado(estado: str) -> dict:
    print(f'[ ] Buscando informações de {estado}...')
    url_estado = f'https://www.ibge.gov.br/cidades-e-estados/{estado}.html'
    pagina = requests.get(url_estado, verify=False)

    soup = BeautifulSoup(pagina.content, 'html.parser')
    indicadores = soup.select('.indicador')

    estado_dict = {
        ind.select('.ind-label')[0].text: ind.select('.ind-value')[0].text
        for ind in indicadores
    }

    estado_dict['Estado'] = estado

    return estado_dict

In [13]:
estados = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']

dados_estados = [extrair_info_estado(estado) for estado in estados]

[ ] Buscando informações de AC...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de AL...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de AP...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de AM...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de BA...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de CE...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de DF...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de ES...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de GO...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de MA...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de MT...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de MS...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de MG...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de PA...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de PB...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de PR...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de PE...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de PI...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de RJ...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de RN...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de RS...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de RO...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de RR...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de SC...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de SP...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de SE...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

[ ] Buscando informações de TO...

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.ibge.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [16]:
df = pd.DataFrame(dados_estados)
df.head()

,Governador,Capital,Gentílico,Área Territorial,População residente,Densidade demográfica,Matrículas no ensino fundamental,IDH Índice de desenvolvimento humano,Total de receitas brutas realizadas,Total de despesas brutas empenhadas,Rendimento mensal domiciliar per capita,Total de veículos,Estado
0,GLADSON DE LIMA CAMELI [2023],Rio Branco [2010],acriano,"164.173,525 km² [2023]",830.018 pessoas [2022],"5,06 hab/km² [2022]",147.350 matrículas [2023],"0,71 [2021]","11.137.410.342,21 R$ [2023]","10.302.403.420,85 R$ [2023]",1.095 R$ [2023],350.273 veículos [2023],AC
1,PAULO SURUAGY DO AMARAL DANTAS [2023],Maceió [2010],alagoano,"27.830,661 km² [2023]",3.127.683 pessoas [2022],"112,38 hab/km² [2022]",439.014 matrículas [2023],"0,684 [2021]","20.927.817.222,51 R$ [2023]","17.963.587.096,92 R$ [2023]",1.110 R$ [2023],1.095.144 veículos [2023],AL
2,CLÉCIO LUÍS VILHENA VIEIRA [2023],Macapá [2010],amapaense,"142.470,762 km² [2023]",733.759 pessoas [2022],"5,15 hab/km² [2022]",131.948 matrículas [2023],"0,688 [2021]","11.249.572.238,02 R$ [2023]","8.505.172.844,49 R$ [2023]",1.520 R$ [2023],242.574 veículos [2023],AP
3,WILSON MIRANDA LIMA [2023],Manaus [2010],amazonense,"1.559.256,365 km² [2023]",3.941.613 pessoas [2022],"2,53 hab/km² [2022]",692.623 matrículas [2023],"0,7 [2021]","33.030.751.885,07 R$ [2023]","30.029.370.828,75 R$ [2023]",1.172 R$ [2023],1.130.055 veículos [2023],AM
4,JERÔNIMO RODRIGUES SOUZA [2023],Salvador [2010],baiano,"564.760,429 km² [2023]",14.141.626 pessoas [2022],"25,04 hab/km² [2022]",1.865.574 matrículas [2023],"0,691 [2021]","80.290.524.858,16 R$ [2023]","77.868.037.416,52 R$ [2023]",1.139 R$ [2023],5.120.353 veículos [2023],BA

# Limpeza

In [17]:
estados_df = df.copy()
estados_df.columns = ['governador', 'capital', 'gentílico', 'área', 'população', 'densidade_demográfica', 'matrículas_ensino_fundamental', 'idh', 'receita_realizada', 'despesas_empenhadas', 'renda_per_capita', 'total_veículos', 'código']
estados_df = estados_df[['código', 'governador', 'população', 'área', 'idh', 'renda_per_capita', 'total_veículos', 'matrículas_ensino_fundamental', 'despesas_empenhadas', 'receita_realizada']]

estados_df = estados_df.replace({
    '\.': '',
    ',': '.',
    '\[\d+\]': '',
    ' hab/km²': '',
    ' km²': '',
    ' pessoas': '',
    ' matrículas': '',
    'R\$.*': '',
    ' veículos': ''
}, regex=True)

estados_df.head()

colunas_numericas = ['população', 'área', 'idh', 'renda_per_capita', 'total_veículos', 'matrículas_ensino_fundamental', 'despesas_empenhadas', 'receita_realizada']

estados_df[colunas_numericas] = estados_df[colunas_numericas].apply(lambda x: x.str.strip())
estados_df[colunas_numericas] = estados_df[colunas_numericas].apply(pd.to_numeric)
estados_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   código                         27 non-null     object
 1   governador                     27 non-null     object
 2   população                      27 non-null     int64
 3   área                           27 non-null     float64
 4   idh                            27 non-null     float64
 5   renda_per_capita               27 non-null     int64
 6   total_veículos                 27 non-null     int64
 7   matrículas_ensino_fundamental  27 non-null     int64
 8   despesas_empenhadas            27 non-null     float64
 9   receita_realizada              27 non-null     float64
dtypes: float64(4), int64(4), object(2)
memory usage: 2.2+ KB

In [18]:
estados_df.head()

,código,governador,população,área,idh,renda_per_capita,total_veículos,matrículas_ensino_fundamental,despesas_empenhadas,receita_realizada
0,AC,GLADSON DE LIMA CAMELI,830018,164173.525,0.710,1095,350273,147350,1.030240e+10,1.113741e+10
1,AL,PAULO SURUAGY DO AMARAL DANTAS,3127683,27830.661,0.684,1110,1095144,439014,1.796359e+10,2.092782e+10
2,AP,CLÉCIO LUÍS VILHENA VIEIRA,733759,142470.762,0.688,1520,242574,131948,8.505173e+09,1.124957e+10
3,AM,WILSON MIRANDA LIMA,3941613,1559256.365,0.700,1172,1130055,692623,3.002937e+10,3.303075e+10
4,BA,JERÔNIMO RODRIGUES SOUZA,14141626,564760.429,0.691,1139,5120353,1865574,7.786804e+10,8.029052e+10